// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWtI-zPiyI_4DaXZfW0KAYOI23Jz7wQY',
    appId: '1:1060786696253:web:dc6179e709a0a44f42fa54',
    messagingSenderId: '1060786696253',
    projectId: 'safe-route-c7662',
    authDomain: 'safe-route-c7662.firebaseapp.com',
    storageBucket: 'safe-route-c7662.firebasestorage.app',
    measurementId: 'G-DTJPPTN6CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWtI-zPiyI_4DaXZfW0KAYOI23Jz7wQY',
    appId: '1:1060786696253:android:dc6179e709a0a44f42fa54', // Note: Guessed android appId based on web
    messagingSenderId: '1060786696253',
    projectId: 'safe-route-c7662',
    storageBucket: 'safe-route-c7662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWtI-zPiyI_4DaXZfW0KAYOI23Jz7wQY',
    appId: '1:1060786696253:ios:dc6179e709a0a44f42fa54', // Note: Guessed ios appId based on web
    messagingSenderId: '1060786696253',
    projectId: 'safe-route-c7662',
    storageBucket: 'safe-route-c7662.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWtI-zPiyI_4DaXZfW0KAYOI23Jz7wQY',
    appId: '1:1060786696253:ios:dc6179e709a0a44f42fa54',
    messagingSenderId: '1060786696253',
    projectId: 'safe-route-c7662',
    storageBucket: 'safe-route-c7662.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIWtI-zPiyI_4DaXZfW0KAYOI23Jz7wQY',
    appId: '1:1060786696253:web:dc6179e709a0a44f42fa54',
    messagingSenderId: '1060786696253',
    projectId: 'safe-route-c7662',
    authDomain: 'safe-route-c7662.firebaseapp.com',
    storageBucket: 'safe-route-c7662.firebasestorage.app',
    measurementId: 'G-DTJPPTN6CE',
  );
}
